# Generated by Django 3.2.8 on 2021-10-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_people_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Expenditure',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
