# Generated by Django 3.2.8 on 2021-11-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20211016_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=3600),
            preserve_default=False,
        ),
    ]
